### ISSUE TITLE
ArrayIndexOutOfBoundsException when running migrate-to-git

### ISSUE THREAD

**Issue by dentych** [rtcTo/rtc2git-docker#1]
Hello.

I run RTC 4.0.7 and tried pulling the rtc2git docker image for 4.0.7 and run it.
What I did:
- Started the docker image with interactive mode
- Make workspace in eclipse RTC called source (created from the stream I want to migrate)
- Make a NEW workspace called target, and set its flow target to point to source workspace
- Load the target workspace in the docker container
- Run the migrate-to-git command.

I get the following stacktrace:
https://gist.github.com/dentych/9f94bd4ff15045deb6a45cf06adf66d6

Does anyone know how to solve this? Do you need more log output? I have tried reading through it, it doesn't look like it's much help.

**Comment by reinhapa** [comment]
I've updated the 4.0.7 image, could you try again?

**Comment by dentych** [comment]
Cool, @reinhapa. I'll try again when I get back to work tuesday and let you know how it goes :+1:

**Comment by dentych** [comment]
Hey. I tried the 4.0.7 docker image again.

The status is as follows: I can't seem to get the ArrayIndexOutOfBoundsException anymore. However, I get a RuntimeException: Tag not found instead..
http://pastebin.com/0xcy2y1Z

I tried two different setups:
1.
Source workspace: Contains only the initial changeset
Target workspace: Flow target points to source and is up2date with source (so it also has the initial changeset)

2.
Source workspace: Contains ALL changesets in history
Target workspace: Flow target points to source and contains only the initial changeset.

**Comment by reinhapa** [comment]
Just out of curiosity: Do you have ever used tags within RTC so far?

**Comment by dentych** [comment]
On the stream I'm trying to migrate, we haven't, no. Shouldn't the extension be able to handle no tags? :)

**Comment by reinhapa** [comment]
To be honest: I did not created that part of the client. So I guess it seems to have problems with no tags at all, where I will try to have a look into. Unfortunately I do not have a RTC environment without tags here and will need to set-up one first...

**Comment by dentych** [comment]
Oh, alright. I have another stream that's supposed to have tags. I'll try to run the extension on that as well.

EDIT: I tried it on a stream that supposedly had tags, but the same exception came forward. Many of the work items do NOT have tags, only a very few set of them.

**Comment by reinhapa** [comment]
Is there a way for me to have access on a version, repository that has that behaviour? I do not have an instance where I got not tags on it...

**Comment by dentych** [comment]
Unfortunately that is not possible, as it is on our closed internal network. However, I had a sitdown with one of my colleagues, and we figured out that it was possible to add a tag to all work items at once, so I'll  try that out tuesday, and see if the extension will run then.

**Comment by dentych** [comment]
I tried to add tags to all work items in our entire RTC server. It still gave the exact same issue.

**Comment by reinhapa** [comment]
Is it possible to attach also some of the console output prior the actual exception?

**Comment by dentych** [comment]
Yes. Here you go:
http://pastebin.com/YZWBQgUD

And the metadata log:
http://pastebin.com/eUdYtrU3

**Comment by reinhapa** [comment]
Unfortunately I can not reproduce that error until now. :-(
